steps:
  - id: "Linting and formatting"
    name: "python:3.9-alpine"
    script: |
      pip install flake8 black isort
      FMSG=$(flake8 --ignore=E501 api)
      FEC=$?
      BMSG=$(black --check --diff --no-color --line-length 120 api)
      BEC=$?
      IMSG=$(isort --df --check api)
      IEC=$?
      cat <<EOF > /workspace/message.txt
      # Static code analysis results
      ## Flake8 $([ $FEC -eq 0 ] && echo "passed :heavy_check_mark:" || echo "failed :x:")
      <details><summary>Results</summary>

      \`\`\`
      ${FMSG}
      \`\`\`

      </details>

      ## Black $([ $BEC -eq 0 ] && echo "passed :heavy_check_mark:" || echo "failed :x:")
      <details><summary>Results</summary>

      \`\`\`
      ${BMSG}
      \`\`\`

      </details>

      ## Isort $([ $IEC -eq 0 ] && echo "passed :heavy_check_mark:" || echo "failed :x:")
      <details><summary>Results</summary>

      \`\`\`
      ${IMSG}
      \`\`\`

      </details>
      EOF

      if [ $FEC -eq 0 ] && [ $BEC -eq 0 ] && [ $IEC -eq 0 ]
      then
        echo "0" > /workspace/exit_code.txt
      else
        echo "1" > /workspace/exit_code.txt
      fi

  - id: "Post static code checks to PR"
    name: "ghcr.io/supportpal/github-gh-cli"
    env:
      - "REPO_NAME=$REPO_NAME"
      - "PR_NUMBER=$_PR_NUMBER"
    secretEnv: ["GH_PAT_TOKEN"]
    script: |
      echo $GH_PAT_TOKEN | gh auth login --with-token
      echo Posting to /repos/Idonotknowmyname/$REPO_NAME/issues/$PR_NUMBER/comments
      gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/Idonotknowmyname/$REPO_NAME/issues/$PR_NUMBER/comments \
        -F body=@message.txt
      exit $(cat /workspace/exit_code.txt)

  - id: "Terraform init"
    name: "hashicorp/terraform:1.4.5"
    script: |
      cd terraform && terraform init

  - id: "Terraform plan"
    name: "hashicorp/terraform:1.4.5"
    script: |
      cd terraform
      ERR=$(terraform plan -out plan.out -no-color -var-file prod.tfvars 2>&1)
      EXIT_CODE=$?
      echo $EXIT_CODE > /workspace/exit_code.txt
      if [ $EXIT_CODE -eq 0 ]
      then
        cat <<EOF > /workspace/message.txt
      This PR will be making the following changes to the resources:
      <details>
      <summary>Terraform plan</summary>

      \`\`\`
      $(terraform show -no-color plan.out)
      \`\`\`

      </details>
      EOF
      else
        cat <<EOF > /workspace/message.txt
      Failed to run `terraform plan`:
      <details>
      <summary>Terraform error</summary>

      \`\`\`
      ${ERR}
      \`\`\`

      </details>
      EOF
      fi

  - id: "Post plan to PR"
    name: "ghcr.io/supportpal/github-gh-cli"
    env:
      - "REPO_NAME=$REPO_NAME"
      - "PR_NUMBER=$_PR_NUMBER"
    secretEnv: ["GH_PAT_TOKEN"]
    script: |
      echo $GH_PAT_TOKEN | gh auth login --with-token
      echo Posting to /repos/Idonotknowmyname/$REPO_NAME/issues/$PR_NUMBER/comments
      gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/Idonotknowmyname/$REPO_NAME/issues/$PR_NUMBER/comments \
        -F body=@message.txt
      exit $(cat /workspace/exit_code.txt)

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-token/versions/latest
      env: "GH_PAT_TOKEN"
